### PR TITLE
added lineScatter.yaml with universal plotting stuff

### PR DESCRIPTION
**Pull request by wdwatkins**
Might want to change the name of this config?

### CODE REVIEW

**Comment by wdwatkins** [comment]
To load the config file:

``` r
loadConfig('inst/extdata/lineScatter.yaml')
set.seed(2576)
X <- runif(33)
Y <- runif(33)

gs <- gsplot() %>% points(X,Y,xlab="X",ylab="Y") %>% axis(c(3,4),labels=FALSE)
```

image

**Comment by jordansread** [comment]
@wdwatkins I think if you have the most recent (`master` on `USGS-R/gsplot`) you would see a box, right?

**Comment by jordansread** [comment]
Also, for those loading the package (w/o the source in `inst`)

``` r
loadConfig(system.file('extdata', 'lineScatter.yaml', package = 'gsplot'))
set.seed(2576)
X <- runif(33)
Y <- runif(33)

gs <- gsplot() %>% points(X,Y,xlab="X",ylab="Y") %>% axis(c(3,4),labels=FALSE)
```

**Comment by wdwatkins** [comment]
@jread-usgs Yes, I wasn't updated.  Had some weird build problems.

**Pull request merged**
