### PR TITLE
fix #277 (allows ncol arg for legend "below" and "above")

### LINKED ISSUE #277: legend(location="below") does not honor "ncol" argument
Trying to use `ncol=2` so that the legend arguments do not span past margins horizontally. Coupled with `location="below"` or `location="above"`, ncol does not seem to do anything. It works with all the other locations (toleft, toright, left, bottomleft, topleft, bottomright, etc). 

``` r
gs <- gsplot() %>% 
    points(1,2, legend.name="stuff") %>% 
    lines(1:5,1:5, legend.name="myline") %>% 
    points(10,10, legend.name="mypoints") %>% 
    abline(v=6, legend.name="vertical line") %>% 
    rect(2,2,5,3, col="green", border=NA, legend.name="myrectangle") %>%
    lines(6:8,8:6, col="purple", legend.name="another line") %>% 
    points(8,3, legend.name="another set of points") %>% 
    points(3,4, legend.name="just one more set") %>% 
    legend(location="below", ncol=2)
gs
```

image

``` r
gs <- gsplot() %>% 
    points(1,2, legend.name="stuff") %>% 
    lines(1:5,1:5, legend.name="myline") %>% 
    points(10,10, legend.name="mypoints") %>% 
    abline(v=6, legend.name="vertical line") %>% 
    rect(2,2,5,3, col="green", border=NA, legend.name="myrectangle") %>%
    lines(6:8,8:6, col="purple", legend.name="another line") %>% 
    points(8,3, legend.name="another set of points") %>% 
    points(3,4, legend.name="just one more set") %>% 
    legend(ncol=2)
gs
```

image

### PR DESCRIPTION
**Pull request by lindsayplatt**

### CODE REVIEW

**Comment by lindsayplatt** [comment]
failing due to that xaxs='o' test

**Comment by ldecicco-USGS** [comment]
My vote is to take that test out. I haven't looked much at the "o" stuff, but my understanding is that it acts differently than the other xaxs parameters. I don't think that's a good way to do it, so we might need a fair amount of re-work. Or not, and if not, then we can put the test back in when it's working.

**Comment by lindsayplatt** [comment]
It does because it's one we decided would be nice to have - ultimately it is calling xaxs='i'. I'll comment the test out for now!

**Comment by ldecicco-USGS** [comment]
I understand, and I used to have that opinion (keep in breaking tests for critical features). But...@jread-usgs finally convinced me to change my ways. Now I'm thinking more that tests are only for things we know work and don't want to break in the future. Issues are for things that come up. There are a few things I'll want to do before we get to the "o" issue...so it's good to have working tests.

**Comment by lindsayplatt** [comment]
Yeah, I knew it was breaking it too -- the little red x's are actually pretty disheartening

**Comment by lindsayplatt** [comment]
@ldecicco-USGS @jread-usgs any idea what that AppVeyor error is? It doesn't seem to be related to anything I have added but I could be wrong

**Comment by jordansread** [comment]
is related to a storage issue with the R iso I think.

**Comment by lindsayplatt** [comment]
so out of our hands?

**Comment by jordansread** [comment]
I just rebuilt it and it seems fine. 

:+1:

**Pull request merged**
