### PR TITLE
highlight the sugar of gsplot (WIP)

### PR DESCRIPTION
**Pull request by lindsayplatt**
WIP

Looks like:
image

### CODE REVIEW

**Comment by jordansread** [comment]
nice and short. I like it

**Comment by jordansread** [comment]
is "falling back to `graphics`" sugar too? e.g., 

gsplot() %>% points(1,2)
points(2,3)

**Comment by lindsayplatt** [comment]
I would say yes, that is some sugar!

**Comment by lindsayplatt** [comment]
this should be good to go once the checks pass

**Pull request merged**
