### PR TITLE
Revert "Data frame"

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
Reverts USGS-R/gsplot#411

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
FYI @jread-usgs the gsplot object itself had all the right information for the axis (it seemed to me)...it just wasn't printing it. I haven't had a chance to try to troubleshoot.

**Comment by lindsayplatt** [comment]
could be related to strange printing behavior noted in #414

**Comment by ldecicco-USGS** [comment]
When I reverted, that wasn't fixed.

**Comment by lindsayplatt** [comment]
hmm maybe it was with #410 then? It was definitely post #398 and I think I've used whatever is on the master branch since August 15th when your knitr changes were merged.

**Comment by jordansread** [comment]
either way, I was sloppy and didn't knit :(

**Pull request merged**
