### PR TITLE
defaults for yaml and legend.R

### PR DESCRIPTION
**Pull request by lindsayplatt**

### CODE REVIEW

**Comment by jordansread** [comment]
anything you can do about the package check failures? Can you run "check" on your local build? @lindsaycarr

**Comment by ldecicco-USGS** [comment]
I'm guessing something with the change to the MaumeeUV data. I originally put those in for fancy real-world examples.

**Comment by lindsayplatt** [comment]
I don't think I actually changed anything in that file...not knowingly anyways.

**Comment by lindsayplatt** [comment]
I had too many pipes in my rect() example, so now it passed the check on my computer. Unfortunately, my commits for adding a rectangle function today are getting pulled together with my commits from the other day for legend defaults. And that is due to using just the one branch?

**Comment by jordansread** [comment]
yes. We can do branches some day :game_die:

**Comment by lindsayplatt** [comment]
I'll just make sure I don't have unrelated commits for now - still not passing the checks though :disappointed:

**Comment by jordansread** [comment]
Good to go

**Comment by ldecicco-USGS** [comment]
I'm just taking that data out for now, we're not using it anyway.

**Comment by jordansread** [comment]
:100:

**Pull request merged**
