### PR TITLE
Legend NULL fix

### LINKED ISSUE #65: Null legend
Need a way to specify that a data set (line, points, abline) doesn't show up in the legend. For example, maybe a user want's to put a 1:1 line and not have it show up in the legend. So:

``` r
gsNew <- gsplot(list())
gsNew <- points(gsNew, y=1, x=2, col="blue", pch=18, legend.name="Points")
gsNew <- lines(gsNew, c(3,4,3), c(2,4,6),legend.name="Lines")
gsNew <- abline(gsNew, v=3, lty=1,legend.name=NULL)
gsNew
```

Currently the default is "Plotted Line"...do we want that to be the default, and specifying NULL to drop that legend info? Or, default means no legend (for that data set)?

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
Fixes #65

....abline still a work-in-progress.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Ack...getting a fix out for:

``` r
#' defaultLegend <- gsplot(list()) %>% 
#'  points(x=1, y=2, side=c(3,2)) %>% 
#'  points(x=3, y=4, side=c(1,4)) %>% 
#'  lines(x=c(3,4,3), y=c(2,4,6)) %>%
#'  lines(x=c(1,2,5), y=c(1,8,5)) %>%  
#'  legend()
#' defaultLegend
#' 
```

have no fear.

**Comment by ldecicco-USGS** [comment]
That weird warning about codoc mismatch was because someone defined the 'usage' section in points...and it didn't match the actual usage. Roxygen2 will automatically create usage sections.

**Comment by jiwalker-usgs** [comment]
That might have been my fault

**Comment by ldecicco-USGS** [comment]
Also fixes #59

**Comment by jordansread** [comment]
now we are cooking with bacon grease.

**Pull request merged**
