### PR TITLE
be able to use formulas and data lists

### PR DESCRIPTION
**Pull request by lindsayplatt**
this once worked...

```r
gs <- gsplot() %>%
    points(y~x, data=list(x=-3:3,y=-3:3))
gs
```

in base:
```r
plot(c(-10,10), c(-10,10))
points(y~x, data=list(x=-3:3,y=-3:3), col="red", pch=20)
```

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Still need to tweak something, but can't seem to figure out what. See #314

**Review by jiwalker-usgs — APPROVED** [review]

**Comment by lindsayplatt** [comment]
@jiwalker-usgs this isn't actually working - I was hoping for some help on how to get over this error:

```r
Error in terms.formula(formula, data = data) : 
  argument is not a valid model
Called from: terms.formula(formula, data = data)
```

**Comment by jiwalker-usgs** [comment]
ah, should have looked at the branch name ;)

**Comment by lindsayplatt** [comment]
Merging @jread-usgs data frame stuff lost the ability to append mutliple axes (maybe that's why those tests got deleted?!)

```r
gs <- gsplot() %>% 
    points(0:1,0:1) %>% 
    axis(side=1, at=c(0.5,1)) %>% 
    axis(side=1, at=c(0.25, 0.75), append=TRUE)
gs
```

**Comment by ldecicco-USGS** [comment]
@jread-usgs I was going to take a crack at trying to fix the various `axis` issues...but I'm wondering if some of the work here would fix some/all/none of them. Do you think you could take a look to see how close/far this PR is from being merged?

**Comment by ldecicco-USGS** [comment]
OK, I think this is pretty close. I'm going to merge, and task see if I can get it running soon.

**Comment by lindsayplatt** [comment]
awesome!

**Pull request merged**
