### PR TITLE
initial commit for #89

### PR DESCRIPTION
**Pull request by jordansread**
``` R
gs <- gsplot()
gsNew <- points(gs, y=1, x=2, xlim=c(0,3),ylim=c(0,3),
             col="blue", pch=18, legend.name="Points")
gsNew <- callouts(gsNew, 2, 1, labels='dog')
gsNew
```

image

There are a few to-do notes in the code comments

### CODE REVIEW

**Comment by jordansread** [comment]
@ldecicco-USGS or @mhines-usgs take a peek?

**Comment by jordansread** [comment]
looks like installs failed on the builds. GH issue?

**Comment by mhines-usgs** [comment]
hah @jread-usgs -> :dog:

**Comment by mhines-usgs** [comment]
This is really cool, Jordan! I'm going to merge so I can test this with your repgen changes locally.

**Comment by jiwalker-usgs** [comment]
One thought I have here is similar to what we were talking with error bars.  Since these callouts may be tied to points, allow them to be declared within the points call?

**Comment by jordansread** [comment]
yep, I think that makes sense moving forward. Still need the low level calls though too.

**Pull request merged**
