### PR TITLE
vignette populated with Maumee data examples

### PR DESCRIPTION
**Pull request by lindsayplatt**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Run:
`devtools::build_vignettes()`
to add the R/html/Rmd to the inst folder. Then we can look at the pretty html in rawgit

**Comment by ldecicco-USGS** [comment]
See:

https://rawgit.com/lindsaycarr/gsplot/master/inst/doc/gsplotIntro.html

**Comment by lindsayplatt** [comment]
cool!

**Comment by ldecicco-USGS** [comment]
I'd vote we 'Suggest' `dplyr` so we don't have to do anything like:

``` r
sapply(sites, function(x) MaumeeDV$Date[which(MaumeeDV$site_no==x)], USE.NAMES=TRUE)
```

@jread-usgs thoughts?

**Comment by ldecicco-USGS** [comment]
The vignette nicely shows that the grid is sucking again...wtf. I'm going to merge it, and we can iterate on what we want in there.

**Comment by lindsayplatt** [comment]
yeah there is also a problem with where the legend is placed when it is outside the plot (see Fig. 4)

**Comment by ldecicco-USGS** [comment]
Also, I'd 'Suggest' `captioner` so we don't have to manually number the figures. I'd prefer `kfigr`....but there was an issue with it the last time I tried it in a vignette. It might be fixed now. One of those would be good if we want to number (and reference if using `kfigr`) the figures.

**Pull request merged**
