### PR TITLE
last additions for yaxs/xaxs = "o"

### PR DESCRIPTION
**Pull request by lindsayplatt**
addresses more of #211

### CODE REVIEW

**Comment by lindsayplatt** [comment]
The logged axis issue is separate from the yaxs="o" (buffer is calculated the same way as non-log scale limits). The error we were seeing is from trying to set the limit as 0 (see #223 for discussion on whether we should have a fix for this). 

A logged axis will work if you don't try to use 0 as one of the limits:

``` r
y <- runif(10,1,40000)
x <- 1:10

gs <- gsplot()  %>%
    points(x,y, ylim=c(10,NA), log='y') 
gs
```

**Comment by lindsayplatt** [comment]
@jread-usgs this should be good to go now (don't want to merge without other eyes on it first)

**Comment by jordansread** [comment]
hmm...did you try knitting the README.Rmd? I did and got some changes to the plots (like the second one attached here). 

image

**Comment by lindsayplatt** [comment]
weird, I just ran that in my environment and got: 

``` r
gs <- gsplot() %>%
  points(y=c(3,1,2,4,5), x=c(1:3,8,80), col="blue", pch=18, legend.name="Points") %>%
  lines(c(3,4,3), c(2,4,6), legend.name="Lines", ylab="logged y axis", xlab="logged x axis", log='xy') %>%
  callouts(x=8, y=4, lwd=2, angle=45, labels="Not sure about this one") %>%
  title("logged axes") %>%
  axis(side=c(1,2,3,4), labels=FALSE, n.minor=4)
gs
```

image

**Comment by lindsayplatt** [comment]
It's weird that the labels are stopping at 50 though, right?

**Pull request merged**
