### PR TITLE
updates for two issues

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
@lindsaycarr review?

**Comment by lindsayplatt** [comment]
Should it always draw side 1 and 2? With your changes, it only draws 2,3 or 1,4 and not the other two axes. Was that the previous behavior?

``` r
gs <- gsplot() %>%
    points(1:10, 1:10, side=4)
gs
```

image

**Comment by jordansread** [comment]
that should be the existing behavior. To test, try it against previous releases of `USGS-R/gsplot` as side=c(1,4) (since side=4 will break, hence the issue).

**Comment by lindsayplatt** [comment]
You're correct! Merging now

**Comment by jordansread** [comment]
note if you want all four, you have to be explicit:

``` r
gs <- gsplot() %>%
    points(1:10, 1:10, side=4) %>% axis(2) %>% axis(3)
gs
```

image

**Comment by lindsayplatt** [comment]
RIght, I think what was really throwing me off is that frame.plot is missing still

**Pull request merged**
